### ISSUE TITLE
Home access without authentication

### ISSUE THREAD

**Issue by timdoes** [ryanmcdermott/react-native-login#1]
Hi,

On first run, I noticed that if you click the Home link on the login view it takes you to the homepage and says "You are authenticated". This is without typing any auth info.

I also noticed that if you click the Login link while on the login view it shrinks the login view to more than half the size.
![screen shot 2015-09-08 at 7 12 35 pm](https://cloud.githubusercontent.com/assets/3385628/9751772/acec1570-565d-11e5-8ac7-dadcbdbf34a6.png)

-Tim

**Comment by ryanmcdermott** [comment]
Ah, good find. Thank you for that. So, this is because the WebView is binding to navigation changes. When a user navigates away from the page, the WebView handler assumes login was successful. This can be deceiving though if perhaps a user clicks a link elsewhere and it goes to the HOME_URL, then the app thinks it's logged in. This isn't a security issue or anything, as the user doesn't get explicitly granted a cookie or something dangerous like that. In fact, if you remove that Home link altogether this problem goes away (kind of a cheesy fix though)

Do you have a proposed fix? I'm up for a clearer check on if they TRULY did log in or not. In a real world app, as in my case where you already have an existing backend and mobile friendly HTML form, a user successfully authenticates and is redirected to the HOME_URL. We could though check if a cookie is truly set. Anyway, let me know!

See this line: https://github.com/ryanmcdermott/react-native-login/blob/master/ReactNativeLogin/App/components/App.js#L44

**Comment by timdoes** [comment]
Ahh...gotcha. Yeah, I assumed the auth wouldn't allow the user to view the Home view until validated successfully. I thought that's why the links were there.

I can create a PR with this feature if you are interested.

**Comment by ryanmcdermott** [comment]
Send one on up @timdoes I always appreciate it!
